apiVersion: v1
kind: Secret
metadata:
  name: brokerage-order-service-secrets
type: Opaque
stringData:
  APP_DEMODATA_USERS_0_PASSWORD: "CHANGEME-stage-admin-password"
  APP_DEMODATA_USERS_1_PASSWORD: "CHANGEME-stage-alice-password"
  APP_DEMODATA_USERS_2_PASSWORD: "CHANGEME-stage-bob-password"
