apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brokerage-order-service
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - brokerage.example.com
      secretName: brokerage-order-service-tls
  rules:
    - host: brokerage.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brokerage-order-service
                port:
                  name: http
